server:
  port: 80
  forward-headers-strategy: framework
spring:
  cloud:
    gateway:
      routes:
        - id: lesson19-route
#          uri: http://127.0.0.1:8080
          uri: lb://lesson19
          predicates:
            - Host=lesson19**.nip.io
          filters:
            - PreserveHostHeader
eureka:

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false